config/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('home.urls')),
]

home/urls.py
from django.urls import path

from home import views

app_name = 'home'

urlpatterns = [
    path('', views.home_page_view, name='homepage')
]

home/models.py
from django.db import models

# Create your models here.

home/forms.py
from datetime import date, timedelta

from django import forms
from django.core.validators import MaxValueValidator
from django.forms import DecimalField, ChoiceField, NullBooleanField


class CalcForm(forms.Form):
    birth_date = forms.DateField(widget=forms.DateInput(attrs={'type': 'date'}),
                                 required=None,
                                 label='OBLICZ WIEK - podaj datę urodzenia',
                                 validators=[MaxValueValidator(limit_value=(date.today() - timedelta(days=1)),
                                                               message='Podaj datę z przeszłości')])
    bmi = NullBooleanField(label='OBLICZ BMI - podaj wagę i wzrost', widget=forms.CheckboxInput, required=None)
    weight = DecimalField(label='WAGA w kg', decimal_places=1, min_value=1, max_value=300, required=None)
    height = DecimalField(label='WZROST w cm', decimal_places=1, min_value=40, max_value=250, required=None)

    glucose_unit = ChoiceField(label='GLUKOZA', choices=(('mg/dl', 'mg/dl'), ('mmol/l', 'mmol/l')), initial='mmol/l',
                               widget=forms.RadioSelect, required=None)
    glucose_val = DecimalField(label='', decimal_places=1, min_value=0, max_value=2000, required=None)
    rr = DecimalField(label='EKG - aby obliczyć  akcję serca podaj odległość RR w mm i przesuw papieru', decimal_places=1, min_value=0, max_value=200, required=None)
    speed = ChoiceField(label='przesuw papieru', choices=(('25', '25 mm/s'), ('50', '50 mm/s')), initial='50',
                        widget=forms.RadioSelect, required=None)
    qt = DecimalField(label='EKG -aby obliczyć QTc podaj odległość QT w mm oraz uzupełnij wyżej odległość RR i przesuw papieru ', decimal_places=1, min_value=0, max_value=200, required=None)

home/views.py
from django.shortcuts import render

from django.shortcuts import render
from home.forms import CalcForm
from home.helpers import calc_age, calc_glucose, calc_bmi, calc_heart_rate, calc_qtc


def home_page_view(request):
    form = CalcForm()

    if request.method == 'POST':
        form = CalcForm(request.POST)
        if form.is_valid():
            cd = form.cleaned_data
            context = {
                'form': form,
                'birth_date': cd['birth_date'],
                'weight': cd['weight'],
                'age': calc_age(cd['birth_date']),
                'glucose_calculated': calc_glucose(cd['glucose_val'], cd['glucose_unit']),
                'bmi': calc_bmi(cd['bmi'], cd['weight'], cd['height']),
                'heart_rate': calc_heart_rate(cd['rr'], cd['speed']),
                'qtc': calc_qtc(cd['rr'], cd['qt'], cd['speed'])
            }
            return render(request, 'home/home.html', context)

    context = {'form': form}
    return render(request, 'home/home.html', context)

home/templates/home/home.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}

{% block content %}

    <div class="alert alert-success" role="alert">
        <ul class="list-group">
            {% if birth_date %}
                <li class="list-group-item">
                    <b> Data urodzenia: </b>{{ birth_date }}&nbsp;&nbsp;&nbsp;&nbsp;<b> Wiek&nbsp;</b>
                    {% for k, v in  age.items %}
                        {% if  v != 0 %}
                            {{ k }} {{ v }}&nbsp;&nbsp;
                        {% endif %}
                    {% endfor %}
                </li>
            {% endif %}

            {% if  bmi %}
                <li class="list-group-item">
                    <b>BMI </b> {{ bmi }}
                    <br>Wykres dla dzieci powyżej 5 roku życia:&nbsp;
    <a class="mylink" target="_blank" href="https://cdn.who.int/media/docs/default-source/child-growth/growth-reference-5-19-years/bmi-for-age-(5-19-years)/bmifa-girls-z-5-19-labels.pdf?sfvrsn=94b20617_4">dziewczynki</a>&nbsp;&nbsp;&nbsp;
    <a class="mylink" target="_blank"  href="https://cdn.who.int/media/docs/default-source/child-growth/growth-reference-5-19-years/bmi-for-age-(5-19-years)/bmifa-boys-z-5-19-labels.pdf?sfvrsn=5775aced_4">chłopcy</a>
                </li>
            {% endif %}
            {% if glucose_calculated %}
                <li class="list-group-item">
                    <b> Glukoza:</b> {{ glucose_calculated.0 }} {{ glucose_calculated.1 }}
                    = {{ glucose_calculated.2 }} {{ glucose_calculated.3 }}
                </li>
            {% endif %}

            {% if  heart_rate %}
                <li class="list-group-item">
                    <b>Akcja serca </b> {{ heart_rate }} /min
                </li>
                {% if qtc %}
                    <li class="list-group-item">
                        <b>QTC </b>&nbsp;
                        Wzór Bazetta {{ qtc.0 }} s; &nbsp;&nbsp;
                        Wzór Fridericii {{ qtc.1 }} s

                    </li>
                {% endif %}

            {% endif %}
        </ul>
    </div>
    <div>
        <form action="" method="post">
            {% csrf_token %}
            {{ form|crispy }}
            <button type="submit" class="btn btn-success">Oblicz</button>
        </form>

        <br>
    </div>

{% endblock content %}

templates/base.html
{% load static %}

<!doctype html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport"
          content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>{% block title %}{% endblock title %}</title>
    <link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}">
    <link rel="stylesheet" href="{% static 'css/main.css' %}">
    <script src="{% static 'scripts/bootstrap.min.js' %}"></script>
</head>
<body>

<nav class="navbar navbar-expand-lg navbar-light bg-light">
    <div class="container-fluid">
        <a class="navbar-brand" href="#">Kalkulator pediatryczny</a>
        <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarText"
                aria-controls="navbarText" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarText">
            <ul class="navbar-nav me-auto mb-2 mb-lg-0">
                <li class="nav-item">
                    <a class="nav-link active" aria-current="page" href="{% url 'home:homepage' %}">Wyzeruj</a>
                </li>

                <li class="nav-item d-flex flex-row-reverse">

                </li>
            </ul>
        </div>
    </div>
</nav>

<div class="container">
    <div class="row">
        <div class="col
">
            {% block content %}
            {% endblock content %}
        </div>
    </div>
</div>

</body>
</html>